### ISSUE TITLE
Add a default test GLTF

### ISSUE THREAD

**Issue by gsimone** [pmndrs/gltf-react-three#1]
The initial screen would be

```
Drag 'n' drop your GLTF file here
or try with Suzanne
```

and it would let you use a provided gltf (I mention suzanne but whatever is CC)

**Comment by SaraVieira** [comment]
Suzanne is the best option I think, let me know what you think

![CleanShot 2021-04-08 at 12 08 30](https://user-images.githubusercontent.com/1051509/114009108-267f6700-9863-11eb-94b8-1495225c8227.png)


Should be live in 5

**Comment by gsimone** [comment]
Perfect :chef_kiss:
