### ISSUE TITLE
Error on animated models

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/gltf-react-three#10]
When uploading a model with an animation, the app gets stuck on "loading..." and the console shows the error:
```
Uncaught (in promise) TypeError: e.targetNames is undefined
```
The error seems to be coming from here in gltfjsx:
https://github.com/pmndrs/gltfjsx/blob/2696fd69e48c9d4e7b04454870f37f379d0fabc3/src/utils/parser.js#L71

The error does not occur when running the gltfjsx CLI so I think there is some error handling missing from gltf-react-three. What's strange is that I can only see one usage of gltfjsx in this repo and that line appears to be running correctly. I added some log statements to `result.js`:
```js
console.log('trying result')
const result = await new Promise((resolve, reject) => gltfLoader.parse(buffer, '', resolve, reject))
console.log('finished result', result)
```
and it prints a result with animations included before throwing the error. I'm not sure why the error happens after parsing is completed.

Attached is a sample file of a cube with a simple position animation.
[animated-cube.zip](https://github.com/pmndrs/gltf-react-three/files/6280361/animated-cube.zip)

**Comment by SaraVieira** [comment]
Hey!

Thank you for providing the zip, will take a look now

**Comment by SaraVieira** [comment]
Found the issue, its this line: https://github.com/pmndrs/gltfjsx/blob/master/src/utils/parser.js#L71

Need to fix, update the package and we are smooth sailing

**Comment by drcmda** [comment]
published saras fix
