### ISSUE TITLE
gltf model - see through/ one side appears invisible?

### ISSUE THREAD

**Issue by MrRyanFloyd** [pmndrs/gltf-react-three#18]
I used the tool over at https://gltf.pmnd.rs/ to auto-generate the code needed to import my gltf model. When rendering the gltf model in blender, the model appears solid, as it should. When rendering using the `useGLTF` hook from `@react-three/drei`, the model appears see-through from one side, as in a similar effect to  `THREE.FrontSide` side prop for material. I tried adding the `side={THREE.DoubleSide}` prop to the mesh component, and also tried changing the near and far FOV values for the camera from `near={0.01} `to `far={20000}` as suggested [here](https://discourse.threejs.org/t/why-can-i-see-through-gltf/14641). I'm not sure if there is something weird with my model, or if I need to enter in some additional material or mesh prop in to render the model correctly.  

I have linked the codesandbox below. Any or help would be appreciated! Thank you 

https://codesandbox.io/s/uy3yb?file=/src/Model.js

**Comment by SaraVieira** [comment]
ohhhh

glad you figured it out
