### ISSUE TITLE
Exported project does not render anything

### ISSUE THREAD

**Issue by hsavit1** [pmndrs/gltf-react-three#19]
Hello,

When I drag and drop my gltf file into gltf.pmdrs.rs, I get this error in the console

```
Uncaught (in promise) Error: THREE.GLTFLoader: Failed to load buffer "Hertbeat.bin".
```

and on the top of the screen all I see is "Loading..." - I assume because of that console error

any ideas? I am definitely trying to drop the gltf file in and not the bin file

**EDIT** fixed by #17

**Comment by hsavit1** [comment]
here is a zip of the gltf file

[Hertbeat.zip](https://github.com/pmndrs/gltf-react-three/files/7339375/Hertbeat.zip)

**Comment by hsavit1** [comment]
Confirmed that #17 fixed my problem 💯 

However, a new problem popped up when i exported the project as a zip and ran it locally. similarly with codesandbox. nothing appears in the browser when i run the project. 

steps:
- download zip
- unpack
- run `npm i --force`
- run `npm run start`

**Comment by SaraVieira** [comment]
It has been merged! Sorry it took literally 3 years
