### ISSUE TITLE
Error when ticking types box

### ISSUE THREAD

**Issue by Enijar** [pmndrs/gltf-react-three#21]
I get this error in the console when using [gltf.pmnd.rs](https://gltf.pmnd.rs/):

```log
Uncaught (in promise) SyntaxError: Unexpected token (17:5)
```

![Screenshot 2022-02-16 at 16 59 42](https://user-images.githubusercontent.com/5284715/154316770-3f218538-b507-41aa-b3a4-c449e5c2c88f.png)

**Comment by SaraVieira** [comment]
Hey!

Gonna take a look at it

**Comment by SaraVieira** [comment]
Hey!

Just pushed a fix, seems to work with Suzanne, can you please try again?

**Comment by Enijar** [comment]
Thanks, this has fixed the issue, and now works for me!
