### ISSUE TITLE
Cannot load gltf compressed with gltfpack to GLTF -> React Three Fiber 

### ISSUE THREAD

**Issue by Ceyhun-Wipelot** [pmndrs/gltf-react-three#22]
Gltf loader isn't set for KTX2 textures and Meshopt decoders

`Uncaught (in promise) Error: THREE.GLTFLoader: setKTX2Loader must be called before loading KTX2 textures`
`Uncaught (in promise) Error: THREE.GLTFLoader: setMeshoptDecoder must be called before loading compressed files`

i am getting these errors when i try to upload a glb file compressed with gltfpack.

**Comment by Ceyhun-Wipelot** [comment]
Sure here is a model compressed with gltfpact. I used (basisu) KTX to compress textures.
[forklift_compressed.zip](https://github.com/pmndrs/gltf-react-three/files/8425749/forklift_compressed.zip)
k

**Comment by SaraVieira** [comment]
Hey!

So sorry, I completely forgot about this issue. 

It's fixed now so if you ever need again we now support KTX2 textures

**Comment by Ceyhun-Wipelot** [comment]
Thanks a lot!
