### ISSUE TITLE
Importing GLTF with separate texture

### ISSUE THREAD

**Issue by Thiti-Dev** [pmndrs/gltf-react-three#24]
The website only allows uploading the single gltf file

and what about the file that comes up with the texture folder and the bin like

- license.txt
- scene.bin
- scene.gltf
- textures
  - Scene_-_Root_baseColor.png
  - xxx.png
  - xxxx.png

I tried droppin scene.gltf into the website
and obviously, it gave me ```THREE.GLTFLoader: Couldn't load texture textures/Scene_-_Root_baseColor.png```

and workaround for this, or do I have to bundle the texture inside the gltf file?

**Comment by SaraVieira** [comment]
Hey!

There is no workaround for that, we only support files with the texture bundled in for now
