### ISSUE TITLE
Instance all option is not working

### ISSUE THREAD

**Issue by flux0uz** [pmndrs/gltf-react-three#25]
Hey,

Great work on this project.

I just wanted to let you know that when you select the `instance all` option the jsx code doesn't work in the sandbox and therefore in my project either. The error returned is the following: 

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

Check the render method of `InstancedModel`.

**Comment by SaraVieira** [comment]
Fixed here https://github.com/pmndrs/gltf-react-three/commit/84baf795f017d61d4a18f707a2a22b3d01032654

Sorry for the issue
