### ISSUE TITLE
The application crashes as soon as a glb is loaded 

### ISSUE THREAD

**Issue by anujkkheria** [pmndrs/gltf-react-three#34]
I dropped a glb file from a folder as the application loaded and It crashed. 
![image](https://github.com/pmndrs/gltf-react-three/assets/70870932/592154cc-0724-435f-bba5-85dd107f55fc)
these are the errors that are displayed in the console

**Comment by SaraVieira** [comment]
Can you send me the glb you used?

**Comment by anujkkheria** [comment]
Sorry sara for delayed relpy. I am Taking a tutorial for Three.js anf this is the resources link with the glb's in 3d folder[[https://drive.google.com/file/d/1TACD...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbTZqWlBVd3VSdFNzLTF6c3EyYkNNc2c1WkJfd3xBQ3Jtc0tsd2F3RXhGaWtiaGNrZnM4ZDVtSDlZNHNGS3Vaa3JEbXRHSUN6NzR2ZEhubk52MzdfN3Q3TUpkcEFIaGhKNEFWU1JmZDVibWhicE04aFlDNlpleWpST01QRHBqMlB1a09xcVBhSklGczZPNFlDVUQ1RQ&q=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1TACDN8qFpi_NW66I4p48R9_MUmx-JT3P&v=FkowOdMjvYo)](url), None of them are loading. I aslo saw an error saying a file plausible.js is missing when I checked it while typing this reply.

**Comment by SaraVieira** [comment]
Hey

Sorry for the delay here, seems some other fixes I made fixed that too
