### ISSUE TITLE
Error: When I am drop file .gltf its loading evrey long and throw an error in network

### ISSUE THREAD

**Issue by ListKelvin** [pmndrs/gltf-react-three#35]
![image](https://github.com/pmndrs/gltf-react-three/assets/92376692/6471938e-a750-4d64-a9e4-c832dc522672)

**Comment by SaraVieira** [comment]
Can you share the file?

**Comment by ListKelvin** [comment]
[monkeyVietnameseHat.zip](https://github.com/pmndrs/gltf-react-three/files/14623119/monkeyVietnameseHat.zip)
This is my file.

**Comment by SaraVieira** [comment]
Hm i also get an error while trying to import it in blender
<img width="1624" alt="CleanShot 2024-03-16 at 17 10 01@2x" src="https://github.com/pmndrs/gltf-react-three/assets/1051509/30c5ae36-d9e4-46e0-ab2c-2f68494972b1">

**Comment by ListKelvin** [comment]
I am render this file use blender 4.0 may be I am export it in the wrong way. When I am drop file export from blender 2.8 it succeed

**Comment by SaraVieira** [comment]
Weird because I have blender 4 too

I think you are exporting as a file with seperate textures but not uploading the textures

**Comment by ListKelvin** [comment]
You are right. I am export in a wrong way. Thanks for reply me <3

**Comment by SaraVieira** [comment]
You are super welcome!!
