### ISSUE TITLE
Textures are not displaying (Couldn't load texture blob error)

### ISSUE THREAD

**Issue by jorjordandan** [pmndrs/gltf-react-three#38]
Hello! I use this site a fair bit to generate jsx. It's a great resource! However, currently textures seem not to be loading, and I get a 'couldn't load texture blob' error. After several attempts with a new model, I checked a file I'm sure worked previously (duck.glb), and still no texture. 

Steps to reproduce should just be try to load a .glb with a texture and see if the texture displays.

If I take the jsx and model, it still works in my app and shows the texture, but the embedded texture just doesn't currently show up on the site. Here's a screenshot with the duck.glb:

<img width="1723" alt="Screen Shot 2024-04-12 at 9 20 42 AM" src="https://github.com/pmndrs/gltf-react-three/assets/4617339/f9b9b52a-ca16-4b90-97af-c769b4265690">

I've attempted on chrome and safari with the same results. Trying to load a embedded gltf results in a stuck loading screen and different error:

<img width="1602" alt="Screen Shot 2024-04-12 at 9 31 46 AM" src="https://github.com/pmndrs/gltf-react-three/assets/4617339/16364501-ea15-455e-be4f-747a45520440">

I took a look through drei issues and didn't see anything directly related.

Thanks!

**Comment by SaraVieira** [comment]
Is it okay for you to share the model?

**Comment by SaraVieira** [comment]
Also super glad you use the website :D

**Comment by jorjordandan** [comment]
Sure! Here's the models I tried: 
https://www.dropbox.com/scl/fo/0817ybw2xdnsihabkddz2/AJTjmO2inQUIoITRuIXi5P4?rlkey=5urtl1fozcihmbgs4mu0zoumv&dl=0

**Comment by SaraVieira** [comment]
omg i swear I have no idea what was wrong, I basically removed the loading manager when it's just one file and that seems to have done the trick, I tried some GLTF, GLB and even a GLTF with a scene.bin and it seems to work :D

Leaving open if you find anything

**Comment by jorjordandan** [comment]
Hey! I cloned the repo and it looks like it's working for those files now, but it seems the deployments are failing for reasons unknown 😅. When I try to run build I get the 'Unknown-property' errors from eslint. I've been just using the ignore directive for r3f files for those in my projects. It seems like an ongoing discussion: https://github.com/jsx-eslint/eslint-plugin-react/issues/3423#issuecomment-1932329802 . WIth that rule disabled on the viewer file, the project seems to build. I can create a PR with that if you'd like :)

**Comment by SaraVieira** [comment]
I am so sorry! 

Would love a PR thank you!
