### ISSUE TITLE
Add credits

### ISSUE THREAD

**Issue by gsimone** [pmndrs/gltf-react-three#4]
I'd add a tiny footer with poimandres logo, a link to the gltfjsx cli - and your personal credit @SaraVieira, if you want

**Comment by SaraVieira** [comment]
Wanna do it? Or want me to do it?

**Comment by SaraVieira** [comment]
It would be great to have the GitHub link too to this project

**Comment by gsimone** [comment]
We do have this package with some branding stuff, maybe we can just reuse it @drcmda wdyt?
